#!/bin/bash
################################################################################
# HIPAA Backup System - Automated Deployment Script
################################################################################

set -e  # Exit on error

echo "=================================="
echo "HIPAA Backup System Deployment"
echo "=================================="
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "Checking prerequisites..."

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not found. Please install: https://aws.amazon.com/cli/${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} AWS CLI installed"

# Check Terraform
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform not found. Please install: https://www.terraform.io/downloads${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} Terraform installed"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm not found. Please install Node.js${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} npm installed"

echo ""
echo "=================================="
echo "Step 1: Configuration"
echo "=================================="
echo ""

# Prompt for configuration
read -p "Enter your notification email address: " NOTIFICATION_EMAIL
read -p "Enter AWS region [ca-central-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-ca-central-1}
read -p "Enter environment (staging/production) [staging]: " ENVIRONMENT
ENVIRONMENT=${ENVIRONMENT:-staging}

echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo "  Email: $NOTIFICATION_EMAIL"
echo "  Region: $AWS_REGION"
echo "  Environment: $ENVIRONMENT"
echo ""

read -p "Is this correct? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Deployment cancelled."
    exit 0
fi

echo ""
echo "=================================="
echo "Step 2: Check MongoDB Secrets"
echo "=================================="
echo ""

echo "Checking if MongoDB URL is in Secrets Manager..."

SECRET_NAME="${ENVIRONMENT}/mongodb-url"

if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" --region "$AWS_REGION" &> /dev/null; then
    echo -e "${GREEN}✓${NC} Secret '$SECRET_NAME' exists"
else
    echo -e "${YELLOW}⚠${NC}  Secret '$SECRET_NAME' not found"
    echo ""
    echo "Would you like to create it now?"
    read -p "Enter MongoDB URL (or 'skip' to create manually later): " MONGODB_URL
    
    if [ "$MONGODB_URL" != "skip" ]; then
        aws secretsmanager create-secret \
            --name "$SECRET_NAME" \
            --description "MongoDB connection URL for $ENVIRONMENT" \
            --secret-string "{\"MONGODB_URL\":\"$MONGODB_URL\"}" \
            --region "$AWS_REGION"
        
        echo -e "${GREEN}✓${NC} Secret created"
    else
        echo -e "${YELLOW}⚠${NC}  Please create secret manually before running backups"
        echo "  Command: aws secretsmanager create-secret --name $SECRET_NAME --secret-string '{\"MONGODB_URL\":\"mongodb+srv://...\"}' --region $AWS_REGION"
    fi
fi

echo ""
echo "=================================="
echo "Step 3: Build Lambda Packages"
echo "=================================="
echo ""

# Build backup Lambda
echo "Building backup Lambda..."
cd lambda-backup
npm install --production
zip -q -r ../lambda-backup.zip .
cd ..
echo -e "${GREEN}✓${NC} lambda-backup.zip created"

# Build verification Lambda
echo "Building verification Lambda..."
cd lambda-verify
npm install --production
zip -q -r ../lambda-verify-backup.zip .
cd ..
echo -e "${GREEN}✓${NC} lambda-verify-backup.zip created"

# Build restore Lambda
echo "Building restore Lambda..."
cd lambda-restore
npm install --production
zip -q -r ../lambda-restore.zip .
cd ..
echo -e "${GREEN}✓${NC} lambda-restore.zip created"

echo ""
echo "=================================="
echo "Step 4: Update Terraform Variables"
echo "=================================="
echo ""

# Create or update tfvars file
TFVARS_FILE="${ENVIRONMENT}-backups.tfvars"

cat > "$TFVARS_FILE" <<EOF
# Auto-generated by deploy-backup-system.sh
environment                = "$ENVIRONMENT"
aws_region                = "$AWS_REGION"
backup_notification_email = "$NOTIFICATION_EMAIL"
EOF

echo -e "${GREEN}✓${NC} Created $TFVARS_FILE"

echo ""
echo "=================================="
echo "Step 5: Terraform Plan"
echo "=================================="
echo ""

echo "Running terraform plan..."
terraform init -upgrade
terraform plan -var-file="$TFVARS_FILE" -out=backup-plan.tfplan

echo ""
echo "=================================="
echo "Step 6: Deploy Infrastructure"
echo "=================================="
echo ""

read -p "Do you want to deploy the backup infrastructure? (yes/no): " DEPLOY_CONFIRM

if [ "$DEPLOY_CONFIRM" != "yes" ]; then
    echo "Deployment cancelled. You can deploy later with:"
    echo "  terraform apply -var-file=\"$TFVARS_FILE\""
    exit 0
fi

echo ""
echo "Deploying..."
terraform apply backup-plan.tfplan

echo ""
echo -e "${GREEN}✓${NC} Deployment complete!"

echo ""
echo "=================================="
echo "Step 7: Confirm SNS Subscription"
echo "=================================="
echo ""

echo -e "${YELLOW}IMPORTANT:${NC} Check your email and confirm the SNS subscription!"
echo "  Look for: 'AWS Notification - Subscription Confirmation'"
echo "  Click the confirmation link to receive backup notifications"
echo ""

read -p "Press Enter once you've confirmed the subscription..."

echo ""
echo "=================================="
echo "Step 8: Test Backup"
echo "=================================="
echo ""

echo "Would you like to trigger a test backup now?"
read -p "(yes/no): " TEST_BACKUP

if [ "$TEST_BACKUP" == "yes" ]; then
    LAMBDA_NAME="${ENVIRONMENT}-mongodb-backup"
    
    echo "Invoking backup Lambda..."
    aws lambda invoke \
        --function-name "$LAMBDA_NAME" \
        --payload '{"backupType":"daily","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%S)'Z"}' \
        --region "$AWS_REGION" \
        test-backup-response.json
    
    echo ""
    echo "Response:"
    cat test-backup-response.json
    echo ""
    
    echo -e "${GREEN}✓${NC} Test backup triggered"
    echo ""
    echo "Check CloudWatch Logs: /aws/lambda/$LAMBDA_NAME"
    echo "Check S3 Bucket: ${ENVIRONMENT}-bianca-hipaa-backups"
    echo "Check your email for backup notification"
fi

echo ""
echo "=================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "=================================="
echo ""
echo "Your HIPAA-compliant backup system is now active."
echo ""
echo "Next Steps:"
echo "  1. ✅ Confirm SNS email subscription (if not already done)"
echo "  2. ⏰ Wait for first automated backup at 2 AM EST"
echo "  3. 📊 Monitor: https://console.aws.amazon.com/cloudwatch/home?region=$AWS_REGION#dashboards:name=${ENVIRONMENT}-hipaa-backup-monitoring"
echo "  4. 📁 Verify backups: https://s3.console.aws.amazon.com/s3/buckets/${ENVIRONMENT}-bianca-hipaa-backups"
echo ""
echo "Documentation:"
echo "  📖 Full guide: HIPAA_BACKUP_DEPLOYMENT_GUIDE.md"
echo "  📞 Troubleshooting: See deployment guide"
echo ""
echo "To manually trigger backups:"
echo "  aws lambda invoke --function-name ${ENVIRONMENT}-mongodb-backup --payload '{\"backupType\":\"daily\"}' response.json --region $AWS_REGION"
echo ""
echo "To restore from backup (CAUTION - overwrites database):"
echo "  aws lambda invoke --function-name ${ENVIRONMENT}-mongodb-restore --payload '{\"CONFIRM_RESTORE\":\"YES_I_WANT_TO_RESTORE\",\"backupKey\":\"daily/backup-XXX.gz\"}' response.json --region $AWS_REGION"
echo ""
echo -e "${GREEN}Thank you for implementing HIPAA-compliant backups!${NC}"
echo ""












