AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ECSCluster:
    Type: String
    Description: "The name of the ECS cluster"
  ECSService:
    Type: String
    Description: "The name of the ECS service"
  AppImageUri:
    Type: String
    Description: "The URI of the Docker image in ECR"
    Default: "730335291008.dkr.ecr.us-east-2.amazonaws.com/bianca-app-backend"

Resources:
  BiancaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::730335291008:role/service-role/codebuild-bianca-service-role
      ArtifactStore:
        Type: S3
        Location: bianca-codepipeline-artifact-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: slampenny
                Repo: bianca-app-backend
                Branch: main
                OAuthToken: !Sub '{{resolve:secretsmanager:MySecretsManagerSecret:SecretString:GitHubToken}}'
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: bianca  # Ensure this matches your actual CodeBuild project name
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ClusterName: !Ref ECSCluster
                ServiceName: !Ref ECSService
                FileName: imagedefinitions.json
              RunOrder: 1
