import React, { useLayoutEffect } from "react"
import { StyleSheet, View, ScrollView, Platform } from "react-native"
import { useNavigation } from "@react-navigation/native"
import { spacing, typography } from "app/theme"
import { Text } from "app/components"
import { useTheme } from "app/theme/ThemeContext"
import { translate } from "app/i18n"
import type { ThemeColors } from "../types"
import Markdown from 'react-native-markdown-display'

const PRIVACY_MD = `
## MyPhoneFriend - Privacy Policy

**Effective Date:** [Date]
**Last Updated:** [Date]

Welcome to MyPhoneFriend ("we," "us," "our"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our MyPhoneFriend mobile application (the "App") and services (collectively, the "Services"). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the app.

We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the "Last Updated" date of this Privacy Policy.

**1. INFORMATION WE COLLECT**

We may collect information about you in a variety of ways. The information we may collect via the App depends on the content and materials you use, and includes:

* **Personal Data:** Personally identifiable information, such as your name, email address, phone number, relationship to the person being called (if applicable), and user account credentials that you voluntarily give to us when you register with the App or when you choose to participate in various activities related to the App. If you are using the App on behalf of an organization (e.g., a retirement home), we may collect information about the organization and your role.
* **Patient/Recipient Information:** If you use the App to initiate calls to another person (e.g., a family member, a patient, a resident - the "Recipient"), you may provide their name and phone number. **You represent and warrant that you have obtained all necessary consents from the Recipient to provide their information to us and for us to contact them via the App's Services.**
* **Call Data and Content:**
    * **Call Recordings:** Phone calls initiated or managed through the App may be recorded. **Appropriate notice and consent for recording will be sought as required by applicable law before recording begins.**
    * **Call Transcriptions:** Audio from recorded calls may be transcribed into text using AI and/or third-party services.
    * **Call Metadata:** Information about the calls, such as date, time, duration, caller number, recipient number.
    * **Wellness Check Information:** Information discussed during the wellness check calls, which may include sensitive information related to health, mood, activities, and well-being. This information may be derived from the recordings and transcriptions.
* **Derivative Data:** Information our servers automatically collect when you access the App, such as your mobile device information (e.g., device ID, model, manufacturer), operating system, version information, IP address, and usage patterns.
* **AI Analysis Data:** Results, summaries, or insights generated by AI processing of call recordings and transcriptions.

**2. HOW WE USE YOUR INFORMATION**

Having accurate information permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the App to:

* Create and manage your account.
* Provide the core functionality of the App, including initiating and managing wellness check calls.
* Record and transcribe calls **where legally permissible and appropriate consent has been obtained.**
* Analyze call recordings and transcriptions using AI to provide wellness summaries, insights, or alerts as part of the Service.
* Enable user-to-user communications (e.g., sharing results between a family member and the recipient, or between a care facility and the recipient/family, based on user settings and consents).
* Improve the App and our Services, including training our AI models. **Data used for AI training will be anonymized and/or aggregated where feasible and appropriate consent will be obtained if required by law.**
* Monitor and analyze usage and trends to improve your experience with the App.
* Notify you of updates to the App.
* Respond to customer service requests.
* Comply with legal obligations.

**3. DISCLOSURE OF YOUR INFORMATION**

We may share information we have collected about you in certain situations. Your information may be disclosed as follows:

* **By Law or to Protect Rights:** If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
* **Third-Party Service Providers:** We may share your information with third parties that perform services for us or on our behalf, including AI transcription services, AI analysis services, data storage, hosting services, customer service, and marketing assistance. These providers will only have access to the information necessary to perform their functions and are obligated to protect your information.
* **With Your Consent / At Your Direction:** We may share your information (including call data, recordings, transcriptions, summaries) with other users or third parties when you explicitly consent or direct us to do so through the App's functionality (e.g., a family member sharing results, a care facility sharing information according to their policies and resident agreements).
* **Business Transfers:** We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
* **Anonymized/Aggregated Data:** We may share anonymized or aggregated data, which cannot reasonably be used to identify you, for various purposes including research or AI model improvement.

**4. CALL RECORDING AND TRANSCRIPTION CONSENT**

**Recording and transcribing phone calls is subject to laws that vary by jurisdiction. Some jurisdictions require consent from all parties on the call.**

* **Our Responsibility:** The App will provide notice mechanisms (e.g., audible announcements at the start of a call) where feasible and legally required, indicating that a call may be recorded and/or transcribed for wellness check purposes.
* **Your Responsibility:**
    * **If you are initiating a call to another person (Recipient):** You are responsible for ensuring that the Recipient has consented to the call being recorded and transcribed by our Service *before* the call proceeds with recording/transcription enabled. You represent and warrant that you have obtained all necessary consents required by applicable law.
    * **If you are an organizational user (e.g., retirement home):** You are responsible for obtaining all necessary consents from your residents/patients and/or their legal representatives, in accordance with applicable laws (including privacy and health information laws) and your own policies, before using the App to call and record/transcribe interactions with them. You agree to indemnify us for any failure to obtain such necessary consents.
* **Refusal/Withdrawal:** Participants may have the right to refuse or withdraw consent for recording/transcription according to applicable law.

**5. SECURITY OF YOUR INFORMATION**

We use administrative, technical, and physical security measures to help protect your personal information, including sensitive health-related information derived from wellness checks. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.

**6. DATA RETENTION**

We will retain your personal information, including call recordings and transcriptions, only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law. Criteria used to determine retention periods include the duration of your user relationship, operational needs, and legal/regulatory obligations.

**7. YOUR PRIVACY RIGHTS**

Depending on your jurisdiction, you may have certain rights regarding your personal information, such as:

* The right to access the personal information we hold about you.
* The right to request correction of inaccurate personal information.
* The right to request deletion of your personal information.
* The right to object to or restrict certain processing.
* The right to withdraw consent (where processing is based on consent).

To exercise these rights, please contact us using the contact information below. We will respond to your request in accordance with applicable laws. Note that we may need to verify your identity before processing your request, and certain information may be exempt from such requests under applicable law.

**8. POLICY FOR CHILDREN**

We do not knowingly solicit information from or market to children under the age of 13 (or a higher age threshold if required by applicable law). If you become aware of any data we have collected from children under the relevant age, please contact us using the contact information provided below.

**9. CONTACT US**

If you have questions or comments about this Privacy Policy, please contact us at:

[Your Company Name]
[Your Company Address]
[Your Email Address]
[Your Phone Number, Optional]
`;

export const PrivacyScreen = () => {
  const navigation = useNavigation()
  const { colors, isLoading: themeLoading } = useTheme()

  // Update header options when theme changes
  useLayoutEffect(() => {
    navigation.setOptions({
      headerTintColor: colors.palette.biancaHeader || colors.text,
      headerStyle: {
        backgroundColor: colors.palette.biancaBackground,
      },
      headerTitleStyle: {
        color: colors.palette.biancaHeader || colors.text,
      },
    })
  }, [navigation, colors])

  if (themeLoading) {
    return null
  }

  const styles = createStyles(colors)
  const markdownStyles = createMarkdownStyles(colors)

  return (
    <View style={styles.container}>
      <ScrollView 
        style={Platform.OS === 'web' ? [styles.scrollView, { 
          height: '100vh',
          maxHeight: '100vh',
        }] : styles.scrollView}
        contentContainerStyle={styles.contentContainer}
        nestedScrollEnabled={true}
        showsVerticalScrollIndicator={true}
        bounces={false}
        alwaysBounceVertical={false}
      >
        <View style={styles.contentCard}>
          <Markdown style={markdownStyles}>{PRIVACY_MD}</Markdown>
        </View>
      </ScrollView>
    </View>
  )
}

const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: {
    backgroundColor: colors.palette.biancaBackground,
    flex: 1,
    height: '100%',
    width: '100%',
    ...(Platform.OS === 'web' && {
      height: '100vh',
      maxHeight: '100vh',
      position: 'relative',
    } as any),
  },
  scrollView: {
    flex: 1,
    height: '100%',
    width: '100%',
    ...(Platform.OS === 'web' && {
      height: '100%',
      maxHeight: '100%',
      overflowY: 'auto',
      overflowX: 'hidden',
      WebkitOverflowScrolling: 'touch',
      position: 'relative',
    } as any),
  },
  contentContainer: {
    padding: spacing.lg,
    paddingBottom: spacing.xl,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.palette.biancaHeader,
  },
  contentCard: {
    backgroundColor: colors.palette.neutral100 || colors.background,
    borderRadius: spacing.sm,
    borderWidth: 1,
    borderColor: colors.palette.biancaBorder || colors.border,
    shadowColor: colors.palette.neutral800 || colors.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    padding: spacing.lg,
  },
})

const createMarkdownStyles = (colors: ThemeColors) => ({
  body: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: typography.primary.normal,
  },
  heading1: {
    color: colors.palette.biancaHeader || colors.text,
    fontSize: 24,
    fontWeight: "bold",
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    fontFamily: typography.primary.bold,
  },
  heading2: {
    color: colors.palette.biancaHeader || colors.text,
    fontSize: 22,
    fontWeight: "bold",
    marginTop: spacing.lg,
    marginBottom: spacing.md,
    fontFamily: typography.primary.bold,
  },
  heading3: {
    color: colors.palette.biancaHeader || colors.text,
    fontSize: 18,
    fontWeight: "600",
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    fontFamily: typography.primary.medium,
  },
  paragraph: {
    marginBottom: spacing.md,
    color: colors.text,
  },
  list_item: {
    marginBottom: spacing.sm,
    color: colors.text,
  },
  strong: {
    color: colors.palette.biancaHeader || colors.text,
    fontWeight: "bold",
  },
  bullet_list: {
    marginBottom: spacing.md,
  },
  text: {
    color: colors.text,
  },
}) 