import React from "react"
import { StyleSheet, View, ScrollView } from "react-native"
import { useNavigation } from "@react-navigation/native"
import { colors, spacing, typography } from "app/theme"
import { Text } from "app/components"
import Markdown from 'react-native-markdown-display'

const PRIVACY_PRACTICES_MD = `
# Notice of Privacy Practices
## MyPhoneFriend Healthcare Communication Services

**Effective Date**: October 15, 2025

---

## YOUR INFORMATION. YOUR RIGHTS. OUR RESPONSIBILITIES.

**THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.**

---

## YOUR RIGHTS

You have the right to:
- Get a copy of your health information
- Correct your health information
- Request confidential communication
- Ask us to limit the information we share
- Get a list of those with whom we've shared your information
- Get a copy of this privacy notice
- Choose someone to act for you
- File a complaint if you believe your privacy rights have been violated

---

## YOUR CHOICES

You have some choices in how we use and share information as we:
- Answer questions from your family and friends about your care
- Provide information about you in disaster relief situations

**We never share your information for marketing or sale of your data.**

---

# YOUR DETAILED RIGHTS

## Get a Copy of Your Health Information

**You can ask to see or get a copy of your health information.**

What you can request:
- Call recordings and transcriptions
- Wellness summaries and AI analysis results
- Medical alerts generated by our system
- Emergency notifications
- Account information and preferences

**How to request**:
- Email: privacy@myphonefriend.com
- Phone: +1-604-562-4263

**Our response**: Within 30 days

---

## Ask Us to Correct Your Health Information

**You can ask us to correct health information that you think is incorrect or incomplete.**

**Our response**: Within 60 days

---

## Request Confidential Communications

**You can ask us to contact you in a specific way or location.**

Examples:
- "Please email me instead of calling"
- "Please contact me on my cell phone only"

We will accommodate all reasonable requests.

---

## Ask Us to Limit What We Use or Share

**You can ask us not to use or share certain health information.**

We must agree if you paid out-of-pocket in full and ask us not to share with your health plan.

---

## Get a List of Disclosures

**You can ask for an "accounting of disclosures"** - a list of times we've shared your health information.

Covers: Past 6 years  
Excludes: Disclosures for treatment, payment, and operations (unless you request)

---

## File a Complaint

**File with us**:
- Email: privacy@myphonefriend.com
- Phone: +1-604-562-4263

**File with HHS**:
- Website: https://www.hhs.gov/hipaa/filing-a-complaint
- Phone: 1-800-368-1019

**We will not retaliate against you for filing a complaint.**

---

# OUR USES AND DISCLOSURES

## How We Use Your Health Information

**For Treatment**:
- Provide AI wellness summaries to your caregivers
- Generate emergency alerts for urgent situations
- Enable caregivers to monitor your wellbeing
- Facilitate communication with your care team

**For Payment**:
- Bill your healthcare organization for services
- Process invoices for call time and analysis

**For Healthcare Operations**:
- Improve our AI detection algorithms
- Quality assurance and improvement
- Training our systems to better serve patients

---

## Who We Share With

**Your Healthcare Organization**:
- Your assigned caregivers and care coordinators
- Organization administrators for billing

**Business Associates** (Service Providers):
- AI Services (Azure OpenAI): For transcription and analysis
- Voice Services (Twilio): For phone call handling
- Cloud Hosting (AWS): For secure data storage
- Database (MongoDB Atlas): For data management

All business associates sign Business Associate Agreements and must protect your information.

**As Required by Law**:
- Emergency services (911) if emergency detected
- Public health authorities (abuse, neglect reporting)
- Law enforcement (with valid legal order)

**We Do NOT**:
- ❌ Sell your health information
- ❌ Share with marketers or advertisers
- ❌ Use for marketing without your authorization
- ❌ Share on social media

---

# HEALTH INFORMATION WE COLLECT

**During Use of Our Services**:
- Patient name, phone number, date of birth
- Call recordings and transcriptions
- Health-related information from calls (symptoms, medications, mood)
- Emergency alerts and incidents
- Wellness trends and patterns
- Caregiver notes and observations
- Medical analysis results from AI

---

# YOUR RESPONSIBILITIES

**If you are using our service to call another person**, you are responsible for:
- Obtaining necessary consents for recording
- Ensuring they understand the service
- Following applicable recording consent laws

---

# BREACH NOTIFICATION

**If your health information is improperly accessed or disclosed**, we will:
- Investigate the incident
- Notify you within 60 days if reportable breach
- Explain what happened and what we're doing
- Provide information on steps you can take

---

# CHANGES TO THIS NOTICE

- We may change this notice and changes will apply to all information we have
- New notice will be available in the app and on our website
- You can always request a current copy

---

# CONTACT INFORMATION

**Privacy Officer**:
- Email: privacy@myphonefriend.com
- Phone: +1-604-562-4263
- Mail: MyPhoneFriend Privacy Office, 2955 Elbow Place, Port Coquitlam, BC V3B 7T3

**Hours**: Monday-Friday, 9 AM - 5 PM PST

---

# FILE A COMPLAINT

**With Us**:
- Email: privacy@myphonefriend.com
- Phone: +1-604-562-4263

**With Federal Government (HHS)**:
- Website: https://www.hhs.gov/hipaa/filing-a-complaint
- Phone: 1-800-368-1019
- Mail: Office for Civil Rights, U.S. Department of Health and Human Services, 200 Independence Avenue S.W., Washington, D.C. 20201

---

**Effective Date**: October 15, 2025  
**Version**: 1.0

This Notice of Privacy Practices complies with HIPAA Privacy Rule (45 CFR §164.520)

---

## Language Assistance

**English**: If you need help understanding this notice, contact privacy@myphonefriend.com

**Español**: Si necesita ayuda, comuníquese con privacy@myphonefriend.com
`;

export const PrivacyPracticesScreen = () => {
  const navigation = useNavigation()
  
  return (
    <View style={styles.container}>
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.contentContainer}>
        <View style={styles.contentCard}>
          <Markdown style={markdownStyles}>{PRIVACY_PRACTICES_MD}</Markdown>
        </View>
      </ScrollView>
    </View>
  )
}

const createStyles = (colors: any) => StyleSheet.create({
  container: {
    backgroundColor: colors.palette.biancaBackground,
    flex: 1,
    height: '100%',
    width: '100%',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
  },
  contentCard: {
    backgroundColor: colors.palette.neutral100,
    borderRadius: spacing.sm,
    borderWidth: 1,
    borderColor: colors.palette.biancaBorder,
    shadowColor: colors.palette.neutral800,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    padding: spacing.lg,
  },
})

const markdownStyles = {
  body: {
    color: colors.palette.neutral800,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: typography.primary.normal,
  },
  heading1: {
    color: colors.palette.biancaHeader,
    fontSize: 24,
    fontWeight: "bold",
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    fontFamily: typography.primary.bold,
  },
  heading2: {
    color: colors.palette.biancaHeader,
    fontSize: 22,
    fontWeight: "bold",
    marginTop: spacing.lg,
    marginBottom: spacing.md,
    fontFamily: typography.primary.bold,
  },
  heading3: {
    color: colors.palette.biancaHeader,
    fontSize: 18,
    fontWeight: "600",
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    fontFamily: typography.primary.medium,
  },
  paragraph: {
    marginBottom: spacing.md,
    color: colors.palette.neutral700,
  },
  list_item: {
    marginBottom: spacing.sm,
    color: colors.palette.neutral700,
  },
  strong: {
    color: colors.palette.biancaHeader,
    fontWeight: "bold",
  },
  bullet_list: {
    marginBottom: spacing.md,
  },
}












