#!/bin/bash

# Setup script for Asterisk diagnostic tools
# This script makes the diagnostic scripts executable

echo "🔧 Setting up Asterisk Diagnostic Scripts..."
echo "============================================="

# Make scripts executable
chmod +x diagnose-audio-flow.sh
chmod +x monitor-call.sh

echo "✅ Made scripts executable"
echo ""
echo "📋 Usage Instructions:"
echo "======================"
echo ""
echo "1. Copy these scripts to your Asterisk EC2 instance:"
echo "   scp -i your-key.pem diagnose-audio-flow.sh ec2-user@YOUR_ASTERISK_IP:~/"
echo "   scp -i your-key.pem monitor-call.sh ec2-user@YOUR_ASTERISK_IP:~/"
echo ""
echo "2. SSH into your Asterisk instance:"
echo "   ssh -i your-key.pem ec2-user@YOUR_ASTERISK_IP"
echo ""
echo "3. Run the diagnostic script:"
echo "   ./diagnose-audio-flow.sh"
echo ""
echo "4. For real-time monitoring during a call:"
echo "   ./monitor-call.sh"
echo ""
echo "5. Alternative: Run individual commands manually:"
echo "   # Check Asterisk status"
echo "   sudo docker exec asterisk asterisk -rx 'core show channels'"
echo ""
echo "   # Check bridges"
echo "   sudo docker exec asterisk asterisk -rx 'bridge show all'"
echo ""
echo "   # Enable RTP debugging"
echo "   sudo docker exec asterisk asterisk -rx 'rtp set debug on'"
echo ""
echo "   # Watch RTP packets"
echo "   sudo tcpdump -i eth0 -n -s0 udp and portrange 10000-20000"
echo ""
echo "   # Monitor logs"
echo "   sudo docker logs -f asterisk"
echo ""
echo "🔍 The diagnostic script will help you identify:"
echo "- If Asterisk is receiving calls"
echo "- If channels are being created"
echo "- If bridges are being created"
echo "- If RTP packets are flowing"
echo "- If there are network connectivity issues"
echo ""
echo "📞 The monitoring script will show real-time data during a call"
echo "to help you see exactly where the audio flow breaks down." 