const PDFDocument = require('pdfkit');
const crypto = require('crypto');

/**
 * Build a PDF buffer for consent audit export with a SHA-256 fingerprint over canonical row data.
 * The fingerprint is an integrity seal tying the visible table to the server-generated dataset (not a PKI PDF signature).
 */
function buildConsentAuditPdfBuffer({
  rows,
  scopeLabel,
  generatorEmail,
  generatorRole,
  generatorId,
}) {
  const canonicalRows = rows
    .map((r) => ({
      id: String(r.id || r._id || ''),
      userId: String(r.userId || ''),
      userModel: r.userModel,
      organizationId: r.organizationId || '',
      consentType: r.consentType,
      purpose: r.purpose,
      granted: r.granted,
      withdrawn: r.withdrawn,
      createdAt: r.createdAt,
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const canonicalPayload = JSON.stringify(canonicalRows);
  const digest = crypto.createHash('sha256').update(canonicalPayload).digest('hex');
  const generatedAtUtc = new Date().toISOString();

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 48,
      size: 'LETTER',
      info: {
        Title: 'Consent audit',
        Author: 'Bianca',
        Subject: `Consent audit — ${scopeLabel}`,
        CreationDate: new Date(),
      },
    });

    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(14).font('Helvetica-Bold').text('Bianca — Consent audit report', { align: 'center' });
    doc.moveDown(0.75);
    doc.font('Helvetica').fontSize(10);
    doc.text(`Scope: ${scopeLabel}`);
    doc.text(`Generated (UTC): ${generatedAtUtc}`);
    doc.text(`Prepared by: ${generatorEmail} (${generatorRole}, id: ${generatorId})`);
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text('Document fingerprint (SHA-256 of canonical rows):');
    doc.font('Helvetica').fontSize(8).text(digest, { width: 500 });
    doc.moveDown(0.5);
    doc.fontSize(8).text(
      'This fingerprint verifies that the table below matches the dataset exported at the stated time. It is generated by the Bianca application server; it is not a handwritten signature or a third-party digital certificate.',
      { width: 500, align: 'left' }
    );
    doc.moveDown();

    doc.font('Helvetica-Bold').fontSize(9).text('Records');
    doc.moveDown(0.25);
    doc.font('Helvetica').fontSize(8);

    for (const r of rows) {
      if (doc.y > 720) doc.addPage();
      const orgLabel = r.organizationName || r.organizationId || '—';
      const line1 = `${r.subjectDisplayName || r.userId} | ${r.subjectKind || ''} | ${r.consentType} | granted: ${r.granted} | org: ${orgLabel}`;
      doc.fillColor('#000000').text(line1, { width: 500 });
      const p = String(r.purpose || '')
        .replace(/\s+/g, ' ')
        .slice(0, 220);
      doc.fillColor('#333333').text(`  ${p}`, { width: 500 });
      const via = r.explicitConsent && r.explicitConsent.providedVia ? ` via ${r.explicitConsent.providedVia}` : '';
      doc.text(`  Recorded: ${r.createdAt || '—'}${via}`, { width: 500 });
      doc.moveDown(0.35);
    }

    doc.end();
  });
}

module.exports = {
  buildConsentAuditPdfBuffer,
};
