import { createApi } from "@reduxjs/toolkit/query/react"
import baseQueryWithReauth from "./baseQueryWithAuth"
import { Caregiver, Org, AuthTokens, Patient, Alert } from "./api.types"

export interface SSOLoginRequest {
  provider: 'google' | 'microsoft'
  email: string
  name: string
  id: string
  picture?: string
}

export interface SSOLoginResponse {
  success: boolean
  message: string
  tokens: AuthTokens
  caregiver: Caregiver
  org?: Org
  patients?: Patient[]
  alerts?: Alert[]
}

export interface SSOVerifyRequest {
  provider: 'google' | 'microsoft'
  token: string
}

export interface SSOVerifyResponse {
  success: boolean
  userInfo: {
    id: string
    email: string
    name: string
    picture?: string
  }
}

export const ssoApi = createApi({
  reducerPath: "ssoApi",
  baseQuery: baseQueryWithReauth(), // Use null to get dynamic Config.API_URL
  tagTypes: [],
  endpoints: (builder) => ({
    ssoLogin: builder.mutation<SSOLoginResponse, SSOLoginRequest>({
      query: (data) => ({
        url: "/sso/login",
        method: "POST",
        body: data,
      }),
    }),
    ssoVerify: builder.mutation<SSOVerifyResponse, SSOVerifyRequest>({
      query: (data) => ({
        url: "/sso/verify",
        method: "POST",
        body: data,
      }),
    }),
  }),
})

// Hooks are generated by RTK Query automatically
// If you need to use them, access via: ssoApi.useSSOLoginMutation or ssoApi.useSSOVerifyMutation
// Or use the endpoints directly: ssoApi.endpoints.ssoLogin.initiate()

